theme: jekyll-theme-cayman
future: TRUE
markdown: kramdown

title: MicroFEWs
description: Exploring the Nexus between Food, Energy, and Water <br/> <img src="microfews_logo.svg" width=100 align=center>  
github:
  is_project_page: false
  

# Site Author
author:
  name             : "Your Sidebar Name"
  avatar           : "profile.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Location"
  employer         :
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "http://yourfullgooglescholarurl.com"
  email            :
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  
  

