theme: jekyll-theme-cayman
future: TRUE
markdown: kramdown

title: MicroFEW
description: <img width=200 align=left> <img src="Images/microfews_logo.svg" width=200 align=right> This website is an active repository of the various components of the University of Alaska MicroFEWs team reports, models, codes, and data. The goal of the archive is to preserve all of these various components in one location for long-term accessability and ensure they remain available for future updates as appropriate. 
github:
  is_project_page: false
